### ISSUE TITLE
What is this man?

### ISSUE THREAD

**Issue by KyungtaekAndrew** [seongmin-mun/Corpora#1]

**Comment by KyungtaekAndrew** [comment]
Seong Min, you need to close this issue

**Comment by KyungtaekAndrew** [comment]
Seongmin What time are you going to come tomorrow

**Comment by KyungtaekAndrew** [comment]
Do you wanna go to Costco with me?

**Comment by seongmin-mun** [comment]
> Seongmin What time are you going to come tomorrow

Right after I wake up

**Comment by seongmin-mun** [comment]
Up to you

**Comment by KyungtaekAndrew** [comment]
Ask to your wife

**Comment by seongmin-mun** [comment]
She is calling now

**Comment by seongmin-mun** [comment]
I will let you know when I get her response

**Comment by KyungtaekAndrew** [comment]
What are you doing?

**Comment by KyungtaekAndrew** [comment]
SimSimhae

**Comment by KyungtaekAndrew** [comment]
Gan ba rae Seongmin :muscle:
